---
swagger: '2.0'
info:
  version: 1.0.0
  contact:
    name: Banco Votorantim
    email: bv-arqt@bv.com.br
host: sboot-sprf-base-orch-esteira-resgate-cdb.appuat.bvnet.bv
basePath: "/"
tags:
- name: orchestration-controller
  description: the v1 API
paths:
  "/v1/atacado/esteira-resgate":
    post:
      tags:
      - orchestration-controller
      summary: _esteiraResgateCDB
      operationId: esteiraResgateCDB
      consumes:
      - application/json;charset=utf-8
      produces:
      - application/json
      parameters:
      - in: body
        name: body
        description: esteiraResgateCDB
        required: true
        schema:
          "$ref": "#/definitions/OrchRequestRepresentation"
      responses:
        '200':
          description: Ok
          schema:
            "$ref": "#/definitions/OrchResponseRepresentation"
        '201':
          description: Created
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
          schema:
            "$ref": "#/definitions/OrchErroRepresentation"
      security:
      - basicAuth: []
      deprecated: false
definitions:
  OrchErroRepresentation:
    type: object
    properties:
      code:
        type: integer
        format: int32
        example: 20
      correlationId:
        type: string
        example: 11b31a66-76d1-3a20-9dac-6db59996d5b3
      message:
        type: string
        example: erro de validacao
    title: OrchErroRepresentation
  OrchRequestRepresentation:
    type: object
    required:
    - agencia
    - codigoBanco
    - codigoChaveMovimento
    - codigoEmpresa
    - codigoProduto
    - cpfCnpj
    - dataInclusao
    - dataInicioOperacao
    - dataVencimentoOperacao
    - historico
    - numeroBoleto
    - numeroBoletoOriginal
    - numeroContaCorrente
    - quantidadeOperacao
    - tipoOperacao
    - valorBruto
    - valorLiquido
    - valorOperacao
    - valorPrecoUnitario
    properties:
      agencia:
        type: string
      codigoBanco:
        type: integer
        format: int32
        example: 123456
      codigoChaveMovimento:
        type: string
      codigoEmpresa:
        type: string
      codigoProduto:
        type: integer
        format: int32
        example: 123456
      cpfCnpj:
        type: string
      dataInclusao:
        type: string
        format: date-time
        example: '2017-07-21T17:32:28Z'
      dataInicioOperacao:
        type: string
        format: date
        example: '2017-07-21'
      dataVencimentoOperacao:
        type: string
        format: date
        example: '2017-07-21'
      historico:
        type: string
      numeroBoleto:
        type: string
      numeroBoletoOriginal:
        type: string
      numeroContaCorrente:
        type: string
      quantidadeOperacao:
        type: integer
        format: int64
        example: 123456
      tipoOperacao:
        type: integer
        format: int32
        example: 123456
      valorBruto:
        type: number
      valorIof:
        type: number
      valorIr:
        type: number
      valorLiquido:
        type: number
      valorOperacao:
        type: number
      valorPrecoUnitario:
        type: number
    title: OrchRequestRepresentation
  OrchResponseRepresentation:
    type: object
    properties:
      agencia:
        type: string
      codigoBanco:
        type: integer
        format: int32
        example: 123456
      codigoChaveMovimento:
        type: string
      codigoEmpresa:
        type: string
      codigoMovimento:
        type: integer
        format: int64
      codigoProduto:
        type: integer
        format: int32
        example: 123456
      cpfCnpj:
        type: string
      dataInclusao:
        type: string
        format: date-time
        example: '2017-07-21T17:32:28Z'
      dataInicioOperacao:
        type: string
        format: date
        example: '2020-09-21'
      dataVencimentoOperacao:
        type: string
        format: date
        example: '2017-09-21'
      historico:
        type: string
      numeroBoleto:
        type: string
      numeroBoletoOriginal:
        type: string
      numeroContaCorrente:
        type: string
      quantidadeOperacao:
        type: integer
        format: int64
        example: 123456
      tipoOperacao:
        type: integer
        format: int32
        example: 123456
      valorBruto:
        type: number
      valorLiquido:
        type: number
      valorOperacao:
        type: number
      valorPrecoUnitario:
        type: number
    title: OrchResponseRepresentation
